name: telegram-file-bot
services:
  - name: bot
    type: web
    git:
      branch: main
    env:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
      - TELEGRAM_BOT_TOKEN
      - URL_SECRET
      - BASE_URL
    ports:
      - port: 5000
        protocol: http
    health_check:
      http:
        path: /health
    build:
      dockerfile: Dockerfile
    instance_type: nano
    regions:
      - fra
    scaling:
      min: 1
      max: 1